### ISSUE TITLE
How does ivis compare to UMAP?

### ISSUE THREAD

**Issue by qiangjiaodeyugang** [beringresearch/ivis#104]
I read the paper of this project, find the method is similar with umap(based on KNN). So,what's the differences between these methods?

**Comment by Szubie** [comment]
Probably the biggest difference between ivis and UMAP is what they aim to preserve when reducing dimensionality; UMAP focuses on preservation of local distances between points, while ivis focuses on preserving the global structure of the data. Of course, UMAP does still preserve some global structure, and ivis also preserves some local distances between points too - but each algorithm favors doing one over the other.

We have run a few experiments comparing ivis and other algorithms, including UMAP that indeed suggest that ivis better preserves global structure in the data in some cases - the results are in our docs here: https://bering-ivis.readthedocs.io/en/latest/comparisons.html

**Comment by qiangjiaodeyugang** [comment]
Thank you again for your outstanding work, thank you very much, my problem has been solved.
