### ISSUE TITLE
attempt  to apply non-function 

### ISSUE THREAD

**Issue by Feifei0511** [beringresearch/ivis#116]
I want to install ivis in R, but show the error as the title. The system of my computer is Windows, so I have installed conda before running the code., can anyone help me to solve this problem. thank you! 
library (reticulate)
devtools : : install _github("beringresearch/ivis/R-package")
library (ivis)
model ＜- ivis (k  ＝ 3）
Error in ivis _object$Ivis(embedding _dims ＝ embedding _dims, k ＝ k, distance ＝ distance, : 
    attempt  to apply non-function

**Comment by idroz** [comment]
Hi there!

Before running `ivis`, if you're installing it for the first time you need to call `install_ivis()` in R:

```
devtools::install_github("beringresearch/ivis/R-package")
library(ivis)
install_ivis()
```

That will install all the python requirements - let us know if that helps

**Comment by Feifei0511** [comment]
Thanks for your answer! 
I have called install _ivis() in R in the first time, but there was an error --Error: one or more Python packages failed to install [error code 1]
And I tried to run "pip install ivis ”, but not succeed. 
I don't know where is wrong, So how do I solve it?

**Comment by idroz** [comment]
Hi - Could you provide more details on that error pls - i.e. which python package is failing to install?

Probably has something to do with dependencies - are you installing under WSL?

**Comment by Feifei0511** [comment]
Hi!   This is the detail on that error, I never tried to install under WSL, and I don't how to run in WSL. Could you give me some suggestions?  

> install_ivis()
Creating a virtual environment (ivis)
+ "C:/Users/Admin/AppData/Local/r-miniconda/condabin/conda.bat" "create" "--yes" "--name" "ivis" "python=3.8" "--quiet" "-c" "conda-forge"
Collecting package metadata (current_repodata.json): ...working... done
Solving environment: ...working... done

## Package Plan ##

  environment location: C:\Users\Admin\AppData\Local\R-MINI~1\envs\ivis

  added / updated specs:
    - python=3.8


The following NEW packages will be INSTALLED:

  bzip2              conda-forge/win-64::bzip2-1.0.8-h8ffe710_4
  ca-certificates    conda-forge/win-64::ca-certificates-2022.6.15-h5b45459_0
  libffi             conda-forge/win-64::libffi-3.4.2-h8ffe710_5
  libzlib            conda-forge/win-64::libzlib-1.2.12-h8ffe710_2
  openssl            conda-forge/win-64::openssl-3.0.5-h8ffe710_0
  pip                conda-forge/noarch::pip-22.2.1-pyhd8ed1ab_0
  python             conda-forge/win-64::python-3.8.13-hcf16a7b_0_cpython
  python_abi         conda-forge/win-64::python_abi-3.8-2_cp38
  setuptools         conda-forge/win-64::setuptools-63.2.0-py38haa244fe_0
  sqlite             conda-forge/win-64::sqlite-3.39.2-h8ffe710_0
  tk                 conda-forge/win-64::tk-8.6.12-h8ffe710_0
  ucrt               conda-forge/win-64::ucrt-10.0.20348.0-h57928b3_0
  vc                 conda-forge/win-64::vc-14.2-hb210afc_6
  vs2015_runtime     conda-forge/win-64::vs2015_runtime-14.29.30037-h902a5da_6
  wheel              conda-forge/noarch::wheel-0.37.1-pyhd8ed1ab_0
  xz                 conda-forge/win-64::xz-5.2.5-h62dcd97_1


Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done
+ "C:/Users/Admin/AppData/Local/r-miniconda/condabin/conda.bat" "install" "--yes" "--name" "ivis" "-c" "conda-forge" "ivis[cpu]"
Collecting package metadata (current_repodata.json): ...working... done
Solving environment: ...working... failed with initial frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... failed with initial frozen solve. Retrying with flexible solve.

PackagesNotFoundError: The following packages are not available from current channels:

  - ivis

Current channels:

  - https://conda.anaconda.org/conda-forge/win-64
  - https://conda.anaconda.org/conda-forge/noarch
  - https://repo.anaconda.com/pkgs/main/win-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/win-64
  - https://repo.anaconda.com/pkgs/r/noarch
  - https://repo.anaconda.com/pkgs/msys2/win-64
  - https://repo.anaconda.com/pkgs/msys2/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.


Error: one or more Python packages failed to install [error code 1]

**Comment by Szubie** [comment]
Thanks for bringing this up, the R-package on Windows hasn't been something we use much and developed a few issues. I've pushed a series of commits to the master branch that should hopefully fix the issues you are having.

**Comment by Feifei0511** [comment]
Hi  , thanks for your helping. I tried to reinstall ivis recently, but there was a new error when I run "install _ivis()". I can't understand this error, could you help me to solve this problem? 

＞install _ivis()
raise ReadTimeoutError(self._pool, None, "Read timed out.")
pip._vendor.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out.
Error: Error installing package(s): "\"ivis[cpu]\""
In addition: Warning message:
In shell(fi, intern = intern) :
  'C:\Users\Admin\AppData\Local\Temp\RtmpuOdl3b\filed484fb1424b.bat'The run failed with error code 2

**Comment by idroz** [comment]
This looks to me like an internet connection error. I can’t reproduce it unfortunately.

**Comment by idroz** [comment]
Could you check to see if you can install from command line? I remember seeing that RStudio can have weird proxy settings preventing download from repo with a connection time out error.
