### ISSUE TITLE
Wrong README file referenced in the setup script

### ISSUE THREAD

**Issue by apcamargo** [beringresearch/ivis#23]
Minor bug that I noticed while I was working in a conda-forge recipe for `ivis`. In the setup script, the `README.md` file is referenced, but it is not being packaged with the source (`README.txt` is).

```python
with open('README.md', encoding='utf-8') as f:
    long_description = f.read()
```

**Comment by idroz** [comment]
Thanks for the catch. I removed ``README.txt`` - it looks like it was an old artefact that somehow made its way into the home directory.

Haven't worked with Conda-forge recipes before, but PyPi seems to be reflecting the markdown ``README.md`` . Also, ``long_description_content_type`` seems to be set correctly. It maybe that ``setuptools``, ``twine``, and ``wheel`` need to be upgraded (see here: https://stackoverflow.com/questions/26737222/how-to-make-pypi-description-markdown-work):

* setuptools is upgraded to version 38.6.0 or newer
* twine is upgraded to version 1.11.0 or newer
* wheel is upgraded to version 0.31.0 or newer

Let me know if this works.

**Comment by apcamargo** [comment]
If I build the package locally, README.md is included in the source, but, for some reason, it isn't in the `.tar.gz` file that was uploaded to PyPI. I believe that this be fixed in the next version you upload to PyPI.

Thanks!

**Comment by idroz** [comment]
Great - I uploaded a new minor release to PyPi and GitHub releases. Closing for now, but if issue persists, will reopen. Thanks again for reporting!
