### ISSUE TITLE
Attempt to apply to non-function

### ISSUE THREAD

**Issue by SaskiaFreytag** [beringresearch/ivis#32]
Hi,

I am reviewing for [JOSS-Reviews](https://github.com/openjournals/joss-reviews/issues/1596).

I think I was able to install the package. Unfortunately when I run the example code, I run into the following error:

> model <- ivis(k = 3)
Error in ivis_object$Ivis(embedding_dims = embedding_dims, k = k, distance = distance,  : 
  attempt to apply non-function`

My session info:
```
> sessionInfo()
R version 3.6.0 (2019-04-26)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS Mojave 10.14.4

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.6/Resources/lib/libRlapack.dylib

locale:
[1] en_AU.UTF-8/en_AU.UTF-8/en_AU.UTF-8/C/en_AU.UTF-8/en_AU.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] ivis_1.2.3

loaded via a namespace (and not attached):
[1] compiler_3.6.0  Matrix_1.2-17   tools_3.6.0     yaml_2.2.0      Rcpp_1.0.2      reticulate_1.13
[7] grid_3.6.0      jsonlite_1.6    lattice_0.20-38
```

**Comment by idroz** [comment]
Hi - thanks for trying out ivis!
It looks like the install may not have gone correctly on the Python side. Since R is just a wrapper around the python package, it may be unable to import the ivis library.

Do you get any errors when installing ivis from PyPi?

```
pip install ivis
```

 and then

```python
from ivis import Ivis
```

to make sure everything worked.

**Comment by SaskiaFreytag** [comment]
It works now. I think maybe adding this to the installation guide would be helpful.

Also one way to set the environment variable in R is:
`Sys.setenv(KERAS_BACKEND = "tensorflow")`

**Comment by Feifei0511** [comment]
> It works now. I think maybe adding this to the installation guide would be helpful.
> 
> Also one way to set the environment variable in R is: `Sys.setenv(KERAS_BACKEND = "tensorflow")`

Hi ,I have the same problem with you in R , I set the environment, but not changed, I don't know how to solve it, how did you solve it?
