### ISSUE TITLE
Add contributor guidelines

### ISSUE THREAD

**Issue by SaskiaFreytag** [beringresearch/ivis#34]
This is part of the [JOSS-Review](https://github.com/openjournals/joss-reviews/issues/1596)

Please consider adding clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

**Comment by idroz** [comment]
Hi - I added contributing guidelines and issue report templates to the master branch. Let me know if OK!

**Comment by kevinrue** [comment]
Suggestion for further improving the [CONTRIBUTING.md](https://github.com/beringresearch/ivis/blob/master/CONTRIBUTING.md) file:

> If your PR introduces a change in functionality, make sure you start by writing a design doc.

I suggest providing a template, or at least a minimal description of what you expect as a "design doc".
Without providing a template, you create extra burden on the contributor (guessing) and yourself (explaining) or you could simply scare off prospective contributors.

> Make sure any code you touch still has up-to-date docstrings and documentation.

Suggestion: "any code you _edit_" 

> Write tests.

I suggest inviting contributors to look at https://github.com/beringresearch/ivis/tree/master/tests to learn and follow your testing style.

**Comment by idroz** [comment]
Thanks @kevinrue . I've added the suggested changes, including a link to the design doc template, to the [CONTRIBUTING.md](https://github.com/beringresearch/ivis/blob/master/CONTRIBUTING.md) file.
