### ISSUE TITLE
Loss always going towards 1, all embeddings transform to the same values???

### ISSUE THREAD

**Issue by Hellisotherpeople** [beringresearch/ivis#47]
I have a dataset consisting of 1200D concatonated avg pooled FastText vectors (2 seperate documents going through 2 fasttext models for a total of 4 * 300d vectors per example). 

This dataset properly reduces in dimensionality and projects properly when ran through UMAP, but when ran through Ivis (installed through pip), the loss always goes towards 1 and the embeddings for every example are exactly (err, nearly) the same. 

This seems like a bug. I can't provide you the exact data to reproduce with but it is easy to generate some fasttext word vectors and try ivis on them. 

Example of the what I am seeing for the same data (top is Ivis, bottom is UMAP)  
![image](https://user-images.githubusercontent.com/12686966/65712950-f2f83580-e04c-11e9-903e-79c243d2469f.png)

**Comment by Hellisotherpeople** [comment]
Wow I am a dofus - okay, so I get different embedding values with Ivis but they are extremely close together. My input to both algorithms was vectors that had been MinMaxScaled. 

Is there anything I can do to mitigate this "problem" that I am having with Ivis? I will try to see if I can get my matplotlib graphs to scale properly to see if Ivis actually is projecting properly even with such small difference in 2D vector component values

**Comment by idroz** [comment]
Hi - would you be able to specify dimensionality (i, j) of your input matrix as well as the hyperparameters that you're using to initialise Ivis class?

What happens to the embeddings if you try 1) passing fasttext vectors directly and 2) StandardScaling the vectors?

We're running a lot of fasttext models through ivis internally without any issues, so it certainly is curious to see this result.

**Comment by Hellisotherpeople** [comment]
This was a product of me (accidentally) using the StandardScaler on my data before inputting it to both algorithms. It turns out that in many cases, scaling data is *not* desirable. 

UMAP, while not performing especially well, still seems to handle data like this more elegantly than Ivis

Removing the Scaling operation fixed my issues and Ivis gave me results that were inline with UMAP so I will close this issue for now.
