### ISSUE TITLE
Installing Ivis results in the installation of "tensorflow" even when "tensorflow-gpu" is installed.

### ISSUE THREAD

**Issue by dpfoose** [beringresearch/ivis#50]
**Describe the bug**
Because `tensorflow` is in `setup.py`, installing `ivis` results in the installation of the `tensorflow` package, which is the CPU-only version of Tensorflow, even if the user already has `tensorflow-gpu` installed. When the user subsequently uses Ivis (or anything else dependent on Tensorflow), the CPU version will be used. In order to utilize the GPU version of tensorflow, the user must uninstall `tensorflow` and reinstall `tensorflow-gpu` after installing `ivis`.

**To Reproduce**
`pip install ivis`

**Expected behavior**
The user most likely does not expect the installation of a package that depends on Tensorflow to install the CPU version of Tensorflow when they already have the GPU version installed.

**Additional context**
This has been discussed in tensorflow/tensorflow#7166. One way around this problem is to remove `tensorflow` from the list of requirements in `setup.py` and include it in `extras_require` (see Edward developer @dustinvtran's [comment](https://github.com/tensorflow/tensorflow/issues/7166#issuecomment-282778917)).

**Comment by idroz** [comment]
Thanks for flagging this, @dpfoose . We're just looking at the design aspect around this issue.

In our data sets we notice that only marginal improvements are gained when training ivis on a GPU, hence the decision to install TF-cpu as default. I think that an `if` statement in `setup.py` should do the trick.

**Comment by Szubie** [comment]
Thanks for bringing this to our attention, it is definitely a useful feature to be able to choose between tensorflow-gpu and the cpu-only package depending on your system.

We have made the changes you suggested and merged them into the master branch here: https://github.com/beringresearch/ivis/commit/0fd108eecd1524099c62b3bb862a94813778784e
