### ISSUE TITLE
Handling of mixed type datasets with categorical features

### ISSUE THREAD

**Issue by candalfigomoro** [beringresearch/ivis#58]
From the README file:
> both categorical and continuous features are handled well

How do we handle categorical features? Is one-hot-encoding enough?

In UMAP you can use different distances for one-hot-encoded categorical features (e.g. dice, jaccard etc.) and continuous features, then you perform an "intersection" (see https://github.com/lmcinnes/umap/issues/58).

How can we handle mixed type datasets in ivis? Can we just use it on a dataset with continuous features and one-hot-encoded categorical features mixed together?

Thank you very much

**Comment by idroz** [comment]
Hi - you can mix one-hot-encoded features with continuous. Since OHE will be 0/1, you may also need to scale your continuous features to 0-1 scale as well.

**Comment by candalfigomoro** [comment]
Thank you!
