### ISSUE TITLE
Add JOSS Badge to README

### ISSUE THREAD

**Issue by mpadge** [beringresearch/ivis#60]
Just noticed you don't have the JOSS badge on your README - it would be helpful if you could add the badge to link directly to the corresponding article:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.01596/status.svg)](https://doi.org/10.21105/joss.01596)

**Comment by idroz** [comment]
Thank you! Added in b5f430454f8ffbe237d4a10c3bdfa6a84aecd741.
