### ISSUE TITLE
embedding dim cannot be 1

### ISSUE THREAD

**Issue by HTian1997** [beringresearch/ivis#61]
**Describe the bug**
`embedding_dims` set to be 1 will lead to -> 
ValueError: Invalid reduction dimension 1 for input with 1 dimensions. for 'loss/stacked_triplets_loss/Sum' (op: 'Sum') with input shapes: [?], [] and with computed input tensors: input[1] = <1>.

**To Reproduce**
```python
import numpy as np
from tensorflow.keras.datasets import mnist
from ivis import Ivis

(X_train, Y_train), (X_test, Y_test) = mnist.load_data()
X_train = np.reshape(X_train, (len(X_train), 28 * 28))
X_test = np.reshape(X_test, (len(X_test), 28 * 28))

model = Ivis(embedding_dims=1)
model.fit(X_train, Y_train)
```

**Expected behavior**
It should work when reducing to one dimension. 

**Versions**
 - OS: [GCC 7.3.0] on linux
 - Ivis 1.7.1
 - Python 3.6.7

**Comment by Szubie** [comment]
Hi, thanks for raising this issue. There was an incorrect assumption that it would always be possible to operate on axis=1, but this doesn't hold true for the 1-dimensional embeddings. 

I've pushed a fix for this issue into the master branch here (https://github.com/beringresearch/ivis/commit/78cccf49d4560a16345f45295652beac7cd50db9). Hoping to update the package on PyPI soon as well - will leave the issue open until that's done.


Here's an example of the latest branch working on the iris dataset in 1d, with the expected results:
![iris-1d](https://user-images.githubusercontent.com/13461031/77086996-6f674200-69fa-11ea-88d7-a3e61050b1e1.png)

**Comment by idroz** [comment]
Thanks, @Szubie . I bumped the latest ivis version and uploaded it to PyPi. Feel free to close the issue if it's been resolved.

**Comment by HTian1997** [comment]
@Szubie Thanks!
