### ISSUE TITLE
Cosine distance is not compatible with TF import

### ISSUE THREAD

**Issue by idroz** [beringresearch/ivis#70]
Current behaviour when using `distance='cosine'` throws an error:

```
AttributeError: module 'tensorflow.keras.losses' has no attribute 'cosine_distance'
```

Potential fix is changing module imports to: `tf.compat.v1.losses.cosine_distance`

**Comment by Szubie** [comment]
Fixed cosine distance calculation and made it work across multiple TensorFlow versions here: https://github.com/beringresearch/ivis/commit/9d8eb40f1aff69b890f271f0756b0fcbdc493ba1
