### ISSUE TITLE
classification_weight Parameter

### ISSUE THREAD

**Issue by r0f1** [beringresearch/ivis#97]
Hi, 
The section in the docs about metric learning [here](https://bering-ivis.readthedocs.io/en/latest/metric_learning.html#dimensionality-reduction), talks about a `classification_weight` parameter. However, the Ivis class does not have such a parameter.

Could anyone explain why that is?

**Comment by idroz** [comment]
Good spot - thanks. The parameter was renamed to `supervision_weight` to reflect its applicability to both classification and regression.

I'll update the docs.

**Comment by r0f1** [comment]
Awesome thanks!
