### ISSUE TITLE
Meaning of "Observations" on https://bering-ivis.readthedocs.io/en/latest/hyperparameters.html

### ISSUE THREAD

**Issue by anaconda121** [beringresearch/ivis#99]
I was just looking at the hyperparameters section of the Ivis docs (https://bering-ivis.readthedocs.io/en/latest/hyperparameters.html). I'm a little confused on what observations exactly mean, so any help would be appreciated! Thanks!

**Comment by idroz** [comment]
Hi there - `Observations` is the number of rows in your dataset.

**Comment by anaconda121** [comment]
Thanks!
